version: 2
updates:
  # Keep Dockerfile up to date, batching pull requests weekly
  - package_ecosystem: "docker"
    directory: "v2-apache/"
    schedule:
      interval: "weekly"
  # Keep Dockerfile up to date, batching pull requests weekly
  - package_ecosystem: "docker"
    directory: "v3-nginx/"
    schedule:
      interval: "weekly"
