name: Build images for Docker Hub
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * MON" # Run every Monday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - apache
          - nginx
        variant:
          - ""
          - "-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Build and push ${{ matrix.image }}${{ matrix.variant }}
        uses: docker/bake-action@v1.5.0
        with:
          targets: ${{ matrix.image }}${{ matrix.variant }}
          files: docker-bake.hcl
          push: true
