name: Build images for Docker Hub
on: 
  push:
  schedule:
  - cron: '0 12 * * MON'  # Run every Monday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - v2-apache
          - v3-nginx
        variant:
          - ""
          - "-alpine"

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build ${{ matrix.image }}${{ matrix.variant }}
      run: docker build . -f ${{ matrix.image }}/Dockerfile${{ matrix.variant }}
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -v ${{ matrix.variant }})
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vv ${{ matrix.variant }})
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vvv ${{ matrix.variant }})
           --tag owasp/modsecurity:$(./version.sh ${{ matrix.image }} -vvvv ${{ matrix.variant }})

    - uses: azure/docker-login@v1
      if: github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.dockerhub_user }}
        password: ${{ secrets.dockerhub_token }}

    - name: Push ${{ matrix.image }}${{ matrix.variant }}
      if: github.ref == 'refs/heads/master'
      run: docker push --all-tags owasp/modsecurity
