name: Verify Images
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - apache
          - nginx
        variant:
          - ""
          - "-alpine"
        # Verification can only be done using one platform.
        # This is a limitation on buildx
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: owasp/modsecurity

      - name: Build ${{ matrix.image }}${{ matrix.variant }} - ${{ matrix.platform }}
        uses: docker/bake-action@v2.2.0
        with:
          files: docker-bake.hcl
          targets: ${{ matrix.image }}${{ matrix.variant }}
          set: |
            "${{ matrix.image }}${{ matrix.variant }}.platform=${{ matrix.platform }}"
          pull: true
          load: true

      - name: Run ${{ matrix.image }}${{ matrix.variant }}
        run: |
          TAG=$(docker buildx bake -f docker-bake.hcl --print | jq -r '.target["${{ matrix.image }}${{ matrix.variant }}"].tags[2]')
          docker run -d --name ${{ matrix.image }}${{ matrix.variant }}-test "${TAG}"
          docker logs ${{ matrix.image }}${{ matrix.variant }}-test

      - name: Verify ${{ matrix.image }}${{ matrix.variant }}
        run: |
          docker logs ${{ matrix.image }}${{ matrix.variant }}-test
          [ $(docker inspect ${{ matrix.image }}${{ matrix.variant }}-test --format='{{.State.Running}}') = 'true' ]
