name: Verify Images
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - v2-apache
          - v3-nginx
        variant:
          - ""
          - "-alpine"
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build ${{ matrix.image }}${{ matrix.variant }}
      run: docker build . -f ${{ matrix.image }}/Dockerfile${{ matrix.variant }} --tag test

    - name: Run ${{ matrix.image }}${{ matrix.variant }}
      run: docker run -d --name ${{ matrix.image }}${{ matrix.variant }} test

    - name: Verify ${{ matrix.image }}${{ matrix.variant }}
      run: |
        [ $(docker inspect ${{ matrix.image }}${{ matrix.variant }} --format='{{.State.Running}}') = 'true' ]
