name: Verify Images
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - apache
          - nginx
        variant:
          - ""
          - "-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: owasp/modsecurity

      - name: Build ${{ matrix.image }}${{ matrix.variant }}
        uses: docker/bake-action@v1.5.0
        with:
          files: docker-bake.hcl
          targets: ${{ matrix.image }}${{ matrix.variant }}
          set: |
            "${{ matrix.image }}${{ matrix.variant }}.tags=${{ matrix.image }}${{ matrix.variant }}/test"
          push: false

